# Generated by Django 6.0.6 on 2026-08-08 09:49

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_backfill_default_school"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("school"),
                name="unique_department_name_per_school",
            ),
        ),
    ]
